apps = {
    'Cookie Jam': 'COOKIE JAM',
    'Cookie Jam Blast':'COOKIE JAM BLAST',
    'Panda Pop':'PANDA POP',
    'Snoopy Pop': 'SNOOPY POP',
    'Sugar Smash':'BOOK OF LIFE',
    'Juice Jam':'JUICE JAM',
    'Genies \u0026 Gems':'GENIES AND GEMS',
    'Wild Things':'WILD THINGS',
    'Family Guy: Another Freakin Mobile Game':'FAMILY GUY',
    'Futurama: Worlds of Tomorrow': 'TC - FUTURAMA: WORLDS OF TOMORROW',
    'Harry Potter: Hogwarts Mystery':'HARRY POTTER',
    'Disney Emoji Blitz':'EMOJI BLITZ',
    'Bingo Pop':'BINGO POP',
    'Family Guy: The Quest for Stuff':'TC - FAMILY GUY: THE QUEST FOR STUFF',
    'Mahjong City Tours': 'MAHJONG',
    'World War Doh':'WORLD WAR DOH',
    'Vineyard Valley' : 'VINEYARD VALLEY',
    'Disney Frozen Adventures (COPPA)': 'BLACKFOREST',
    'Bingo Infinity': 'BINGO INFINITY',
    'Solitaire Instant': 'SOLITAIRE',
    'Solitaire Showtime': 'SOLITAIRE SHOWTIME',
    'Disney Frozen Adventures':'BLACKFOREST',
    'Disney Frozen Free Fall (COPPA)': 'FROZEN FREE FALL',
    'Kitty City': 'KITTY CITY',
    'Disney Frozen Free Fall':'FROZEN FREE FALL',
    'Peppy Pairs': 'PEPPY PARIS'
}

apps = {
    'Cookie Jam': 'COOKIE JAM',
    'Cookie Jam Blast':'COOKIE JAM BLAST',
    'Panda Pop':'PANDA POP',
    'Snoopy Pop': 'SNOOPY POP',
    'Sugar Smash':'BOOK OF LIFE',
    'Juice Jam':'JUICE JAM',
    'Genies \u0026 Gems':'GENIES AND GEMS',
    'Wild Things':'WILD THINGS',
    'Family Guy: Another Freakin Mobile Game':'FAMILY GUY',
    'Futurama: Worlds of Tomorrow': 'TC - FUTURAMA: WORLDS OF TOMORROW',
    'Harry Potter: Hogwarts Mystery':'HARRY POTTER',
    'Disney Emoji Blitz':'EMOJI BLITZ',
    'Bingo Pop':'BINGO POP',
    'Family Guy: The Quest for Stuff':'TC - FAMILY GUY: THE QUEST FOR STUFF',
    'Mahjong City Tours': 'MAHJONG',
    'World War Doh':'WORLD WAR DOH',
    'Vineyard Valley' : 'VINEYARD VALLEY',
    'Disney Frozen Adventures (COPPA)': 'BLACKFOREST',
    'Bingo Infinity': 'BINGO INFINITY',
    'Solitaire Instant': 'SOLITAIRE',
    'Solitaire Showtime': 'SOLITAIRE SHOWTIME',
    'Disney Frozen Adventures':'BLACKFOREST',
    'Disney Frozen Free Fall (COPPA)': 'FROZEN FREE FALL',
    'Kitty City': 'KITTY CITY',
    'Disney Frozen Free Fall':'FROZEN FREE FALL',
    'Peppy Pairs': 'PEPPY PARIS'
}

studio_mapping  = {
    'Cookie Jam': 'Jam City',
    'Cookie Jam Blast':'Jam City',
    'Panda Pop':'Jam City',
    'Snoopy Pop': 'Jam City',
    'Sugar Smash': 'Jam City',
    'Juice Jam': 'Jam City',
    'Genies \u0026 Gems':'Jam City',
    'Wild Things':'Jam City',
    'Family Guy: Another Freakin Mobile Game':'Jam City',
    'Futurama: Worlds of Tomorrow': 'Jam City',
    'Harry Potter: Hogwarts Mystery':'Jam City',
    'Disney Emoji Blitz':'Jam City',
    'Bingo Pop':'Toronto',
    'Family Guy: The Quest for Stuff':'Jam City',
    'Mahjong City Tours': 'Berlin',
    'World War Doh':'Jam City',
    'Vineyard Valley' : 'Jam City',
    'Disney Frozen Adventures (COPPA)': 'Jam City',
    'Bingo Infinity': 'Toronto',
    'Solitaire Instant': 'Jam City',
    'Solitaire Showtime': 'Berlin',
    'Disney Frozen Adventures':'Jam City',
    'Disney Frozen Free Fall (COPPA)': 'Jam City',
    'Kitty City': 'Jam City',
    'Disney Frozen Free Fall':'Jam City',
    'Peppy Pairs': 'Berlin'
}