apps = {
    'Cookie Jam': 'COOKIE JAM',
    'Cookie Jam Blast':'COOKIE JAM BLAST',
    'Panda Pop':'PANDA POP',
    'Snoopy Pop': 'SNOOPY POP',
    'Sugar Smash':'BOOK OF LIFE',
    'Juice Jam':'JUICE JAM',
    'Genies \u0026 Gems':'GENIES AND GEMS',
    'Wild Things':'WILD THINGS',
    'Family Guy: Another Freakin Mobile Game':'FAMILY GUY',
    'Futurama: Worlds of Tomorrow': 'TC - FUTURAMA: WORLDS OF TOMORROW',
    'Harry Potter: Hogwarts Mystery':'HARRY POTTER',
    'Disney Emoji Blitz':'EMOJI BLITZ',
    'Bingo Pop':'BINGO POP',
    'Family Guy: The Quest for Stuff':'TC - FAMILY GUY: THE QUEST FOR STUFF',
    'Mahjong City Tours': 'MAHJONG',
    'World War Doh':'WORLD WAR DOH',
    'Vineyard Valley' : 'VINEYARD VALLEY',
    'Disney Frozen Adventures (COPPA)': 'BLACKFOREST',
    'Bingo Infinity': 'BINGO INFINITY',
    'Solitaire Instant': 'SOLITAIRE',
    'Solitaire Showtime': 'SOLITAIRE SHOWTIME',
    'Disney Frozen Adventures':'BLACKFOREST',
    'Disney Frozen Free Fall (COPPA)': 'FROZEN FREE FALL',
    'Kitty City': 'KITTY CITY',
    'Disney Frozen Free Fall':'FROZEN FREE FALL',
    'Peppy Pairs': 'PEPPY PARIS'
}
